name: Streamdal Apollo Server Plugin - Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Streamdal's Apollo Server Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --force

      - name: Release to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

